### ISSUE TITLE
failed to run xv6

### ISSUE THREAD

**Issue by unicornx** [RinHizakura/riscv-emulator#1]
hi, i just tried to load xv6 as below:
```
./build/emu --binary $PATH_TO_XV6_RISCV/kernel/kernel --rfsimg $PATH_TO_XV6_RISCV/fs.img
            Name          Start            end
                              0              0
           .text       80000000           8000
         .rodata       80008000            7f8
           .data       800087f8             4c
            .bss       80009000          1d000
.riscv.attributes              0             35
        .comment              0             28
     .debug_info              0          10fcd
   .debug_abbrev              0           349c
      .debug_loc              0           9e65
  .debug_aranges              0            450
   .debug_ranges              0            800
     .debug_line              0           9dc8
      .debug_str              0            f22
    .debug_frame              0           2cb8
         .symtab              0           1878
         .strtab              0            7fc
       .shstrtab              0             b5

Entry point 0x80000000
There are 1 program headers, starting at offset 64

Program Headers:
Offset              VirtAddr                  PhysAddr
0x1000              0x80000000                0x80000000        
FileSiz             MemSiz               Flags    Align
0x8844              0x26000              0x7      0x1000

Invalid boot rom path.
Failed to run dtc
```

can you please help to have a look? thanks

**Comment by unicornx** [comment]
oh,  I got the answer. dtc is required when running, but I don't have it on my machine. 
After install dtc, I find another issue. In `boot.c`,  dtb_filename is given as "./emu.dtb", it will create the file under the top dir of this project, and make the program failed to load it. I copied it under to ./build and it works.

Anyway, like your emulator very much! :-)

**Comment by RinHizakura** [comment]
First of all, thank you for loving my codes! For the problem that you can't load the `./emu.dtb`, I think that it isn't because you should copy it under the `build` directory. It happens because I didn't wait for my forked process to finish the execution of  `dtc`. See 520063b for the fix. 

If there's still any problem for you, feel free to report to me, thanks!

**Comment by unicornx** [comment]
verified, and it works now.
Raised another issue related to this. You forget removing the file emu.dtb created when make clean ;).

**Comment by unicornx** [comment]
BTW, do you implement MMU support? Sv39 or Sv48? I wonder if xv6 can run on your emulator, mmu should have been supported,  right？ I just had a glance at your code, but have not seen about it, appreciate if you can point it out to me.

**Comment by RinHizakura** [comment]
> Raised another issue related to this. You forget removing the file emu.dtb created when make clean ;).

Thanks! It is fixed now.

For the MMU implementation, only Sv39 is supported for xv6 now. You can find the core function `addr_translate` under file `cpu.c`.
